resource_group_name  = "rg-devops-lab-dev"
location             = "Central US"
vnet_name            = "vnet-devops-lab-dev"
vnet_address_space   = ["10.0.0.0/16"]
subnet_name          = "snet-devops-lab-dev"
subnet_prefix        = "10.0.1.0/24"
vm_name              = "vm-devops-dev-01"
vm_size              = "Standard_D2s_v3"
admin_username       = "azureadmin"
admin_password       = "REDACTED"
environment          = "dev"
create_public_ip     = true
storage_account_name = "stdevopslab001"
